name: Tester

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Cache
      id: cache-tools
      uses: actions/cache@v3.0.2
      with:
        path: |
          ~/bin/*
          ~/.bashrc
        key: ${{ runner.os }}-tools
      
    - name: Install tools
      if: steps.cache-tools.outputs.cache-hit != 'true'
      run: |
        wget http://avellano.usal.es/~compii/INSTALADOR/instaladorcii.sh
        chmod +x instaladorcii.sh
        ./instaladorcii.sh

    - name: Run test
      run: |
        PATH="$PATH:/home/runner/bin" make test
